import { useMemo, useRef, useState, type FormEvent } from 'react';
import { FramePair } from '../FramePair';
import { nodeName, sourceText, type SourceNode, type SourceResolver } from '../SourceView';
import { api } from '../../../api/client';
import { plansApi } from '../../../api/plans';
import { useAppStore } from '../../../store/useAppStore';
import { canLeaveWorkspace } from '../../../components/nutrigo/unsaved-changes';
import { descendants, errorText, fields, leaf, objects, RecordDialog, safeUrl, source, Stateful, useRemote, type ScreenProps } from './shared';
import { agendaDateId as dateId, agendaDateLabel as dateLabel, agendaWeekdays as weekdays, buildAgendaEvents, monthAnchor, wallDate, wallDateId, type AgendaEvent as Event } from './agenda-data';
export { nextConsultation } from './agenda-data';

type Props = ScreenProps & { onConfirm?: (reply: 'attending' | 'needs_change') => Promise<void> | void; onReschedule?: (day: string, time: string) => Promise<void> | void };
const kindLabel = { plan: 'Plan', meal: 'Diario', activity: 'Actividad', consult: 'Consulta' };
const eventColor = { plan:'#c2e66e',meal:'#dff9a2',activity:'#ffcb65',consult:'#ffa257' };
export function NutrigoAgenda({ patient, now = new Date(), onNavigate, onSignOut, onConfirm, onReschedule }: Props) {
  const plan = useRemote(`${patient.id}:agenda-plan`, signal => plansApi.published(patient.id, signal));
  const [month, setMonth] = useState(() => monthAnchor(wallDate(dateId(now)))); const [selected, setSelected] = useState(dateId(now)); const [view, setView] = useState<'month' | 'week' | 'day'>('month'); const [hidden, setHidden] = useState<Set<Event['kind']>>(new Set());
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [status, setStatus] = useState(''); const lock = useRef(false); const refresh = useAppStore(state => state.refreshPatient);
  const [changing, setChanging] = useState(false); const [proposedDay, setProposedDay] = useState(() => patient.appointment?.when.split(' · ')[0] || 'Lunes'); const [proposedTime, setProposedTime] = useState(() => patient.appointment?.when.split(' · ')[1] || '15:00');
  const closeReschedule=()=>{if(canLeaveWorkspace())setChanging(false);};
  const rescheduleDirty=proposedDay!==(patient.appointment?.when.split(' · ')[0]||'Lunes')||proposedTime!==(patient.appointment?.when.split(' · ')[1]||'15:00');
  const all = useMemo(() => buildAgendaEvents(patient, plan.data?.plan ?? null, now), [patient, plan.data, now]);
  const events = all.filter(item => !hidden.has(item.kind)); const selectedEvents = events.filter(item => item.day === selected);
  const toggle = (kind: Event['kind']) => setHidden(previous => { const next = new Set(previous); next.has(kind) ? next.delete(kind) : next.add(kind); return next; });
  const reply = async (value: 'attending' | 'needs_change') => { if (lock.current) return; lock.current = true; setBusy(true); setError(''); setStatus(''); try { if (onConfirm) await onConfirm(value); else { await api.confirmAppointment(patient.id, value); await refresh(patient.id); } setStatus(value === 'attending' ? 'Asistencia confirmada.' : 'Cambio de horario solicitado.'); } catch (caught) { setError(errorText(caught)); } finally { lock.current = false; setBusy(false); } };
  const reschedule = async (event: FormEvent) => { event.preventDefault(); if (lock.current) return; lock.current = true; setBusy(true); setError(''); setStatus(''); try { if (onReschedule) await onReschedule(proposedDay, proposedTime); else { await api.rescheduleAppointment(patient.id, { day: proposedDay, time: proposedTime }); await refresh(patient.id); } setChanging(false); setStatus('Nuevo horario guardado.'); } catch (caught) { setError(errorText(caught)); } finally { lock.current = false; setBusy(false); } };
  const move = (delta: number) => { if (view === 'month') setMonth(current => new Date(Date.UTC(current.getUTCFullYear(), current.getUTCMonth() + delta, 1, 12))); else { const next = wallDate(selected); next.setUTCDate(next.getUTCDate() + delta * (view === 'week' ? 7 : 1)); setSelected(wallDateId(next)); setMonth(monthAnchor(next)); } };
  const cell = (prototype: SourceNode, day: Date, schedule?: SourceNode) => {
    const id = wallDateId(day); const own = events.filter(item => item.day === id); const dayNode = descendants(prototype).find(child => nodeName(child) === 'Day');
    return source(prototype, child => child === prototype ? { tag: 'button', onClick: () => setSelected(id), label: `${dateLabel(id)}, ${own.length} eventos`, props: { 'aria-pressed': selected === id, 'data-calendar-date': id, style: { background:day.getUTCMonth()===month.getUTCMonth()?'#ffffff':'#f6f6f7',boxShadow:selected===id?'inset 0 0 0 2px #c2e66e':undefined } }, children: <>{dayNode ? source(dayNode, child => child===dayNode?{props:{style:{background:id===dateId(now)?'#c2e66e':own.length>1?'#dff9a2':'transparent',borderRadius:4}}}:leaf(child)?{text:day.getUTCDate(),props:{style:{color:day.getUTCMonth()===month.getUTCMonth()?'#272932':'#bebfc2'}}}:undefined) : <span>{day.getUTCDate()}</span>}{own.slice(0, 2).map(item => schedule ? fields(schedule, { '217:7517': item.time, '217:7516': item.title },child=>child===schedule?{props:{style:{background:eventColor[item.kind]}}}:undefined, item.id) : <span key={item.id}>{item.title}</span>)}{own.length > 2 && <span className="text-[10px]">+{own.length - 2}</span>}</> } : undefined, id);
  };
  const resolver: SourceResolver = node => {
    const name = nodeName(node); const text = sourceText(node);
    if(name==='Category List')return {props:{style:{flexWrap:'wrap'}},children:<>{objects(node).map((child,index)=>source(child,resolver,index))}<button type="button" onClick={()=>toggle('meal')} aria-pressed={!hidden.has('meal')} aria-label="Mostrar diario" className="flex items-center gap-[8px] text-[12px]" style={{opacity:hidden.has('meal')?.5:1}}><span aria-hidden="true" style={{background:eventColor.meal,width:16,height:16,borderRadius:4}}/>Diario</button></>};
    if (name === 'Calendar') { const parts = objects(node); const row = parts.find(child => nodeName(child) === 'Row-Calendar-Body'); const prototype = row && objects(row).find(child => nodeName(child) === 'Cell-Calendar-Body'); const head = parts.find(child => nodeName(child) === 'Row-Calendar-Head'); const categories = parts.find(child => nodeName(child) === 'Category List'); if (!row || !prototype) return { children: <Stateful empty="No se pudo cargar el calendario." /> };
      const start = new Date(Date.UTC(month.getUTCFullYear(), month.getUTCMonth(), 1 - month.getUTCDay(), 12)); let count = Math.ceil((month.getUTCDay() + new Date(Date.UTC(month.getUTCFullYear(), month.getUTCMonth() + 1, 0)).getUTCDate()) / 7) * 7;
      if (view === 'week') { const at = wallDate(selected); start.setTime(at.getTime()); start.setUTCDate(at.getUTCDate() - at.getUTCDay()); count = 7; }
      if (view === 'day') { start.setTime(wallDate(selected).getTime()); count = 1; }
      const schedule = descendants(node).find(child => nodeName(child) === 'Schedule');
      return { children: <>{categories && source(categories, resolver)}{view !== 'day' && head && source(head, () => undefined)}{Array.from({ length: Math.ceil(count / 7) }, (_, week) => source(row, child => child === row ? { children: Array.from({ length: Math.min(7, count - week * 7) }, (_, index) => { const day = new Date(start); day.setUTCDate(start.getUTCDate() + week * 7 + index); return cell(prototype, day, schedule); }) } : undefined, week))}</> };
    }
    if (name === 'Right Side') { const prototype = descendants(node).find(child => nodeName(child) === 'Schedule 1'); const header = objects(node).find(child => nodeName(child) === 'Header-Section'); return { children: <>{header && source(header, child => /Button/.test(nodeName(child)) ? { hidden: true } : undefined)}{!selectedEvents.length ? <Stateful empty={`${dateLabel(selected)}: sin eventos.`} /> : prototype && selectedEvents.map(item => fields(prototype, { '217:8305': item.title, '433:18477': item.title }, child => {
      if (nodeName(child) === 'Badge Category') return { text: kindLabel[item.kind],props:{style:{background:eventColor[item.kind]}} };
      if (nodeName(child) === 'Details' && sourceText(child).startsWith('Note ')) return { children: objects(child).map((detail, index) => source(detail, node => leaf(node) && node.tag === 'p' && sourceText(node) !== 'Note' ? { text: item.detail || 'Sin indicaciones adicionales.' } : undefined, index)) };
      if (nodeName(child) === 'Details') return { children: objects(child).map((detail, index) => source(detail, node => leaf(node) ? { text: index === 0 ? dateLabel(item.day) : index === 1 ? item.time : kindLabel[item.kind] } : undefined, index)) };
      if (nodeName(child) === 'Details Note') return { text: item.detail };
      if (nodeName(child) === 'Action') return { children: item.kind === 'consult' ? <div className="flex flex-wrap gap-[8px]"><button type="button" disabled={busy} onClick={() => void reply('attending')} className="rounded-[8px] bg-[#c2e66e] px-[12px] py-[8px] text-[#272932]">Confirmar</button><button type="button" disabled={busy} onClick={() => void reply('needs_change')} className="rounded-[8px] border border-[#e1e1e2] px-[12px] py-[8px]">Pedir cambio</button>{patient.appointment?.channel === 'video' && safeUrl(patient.appointment.meet_url) && <a href={safeUrl(patient.appointment.meet_url)!} target="_blank" rel="noopener noreferrer" className="underline">Entrar a videollamada</a>}</div> : <button type="button" onClick={() => onNavigate(item.kind === 'activity' ? 'ejercicio' : item.kind === 'meal' ? 'diario' : 'plan')} className="rounded-[8px] bg-[#c2e66e] px-[12px] py-[8px] text-[#272932]">Ver {kindLabel[item.kind].toLocaleLowerCase('es')}</button> };
      return undefined;
    }, item.id))}</> }; }
    if (name === 'Card Statistic - Calendar' || (name === '' && (text.startsWith('Total Meal Planning Schedule') || text.startsWith('Meal Planning')) && text.endsWith('agendas'))) { const kind = /Physical/.test(text) ? 'activity' : /Appointments/.test(text) ? 'consult' : 'plan'; return { children: objects(node).map(child => source(child, child => leaf(child) && /^\d+$/.test(sourceText(child)) ? { text: all.filter(item => item.kind === kind).length } : undefined)) }; }
    if (name === 'Div Title' && /September 2028/.test(text)) return { children: <label className="text-[18px]">{month.toLocaleDateString('es-AR', { month: 'long', year: 'numeric', timeZone: 'UTC' })}<input aria-label="Elegir mes" type="month" value={`${month.getUTCFullYear()}-${String(month.getUTCMonth() + 1).padStart(2, '0')}`} onChange={event => { const [year, month] = event.target.value.split('-').map(Number); if (year && month) setMonth(new Date(Date.UTC(year, month - 1, 1, 12))); }} className="ml-[8px] w-[28px] border-0" /></label> };
    if (name === 'Buttons') return { children: objects(node).map((button, index) => source(button, child => child === button ? { onClick: () => move(index ? 1 : -1), label: index ? 'Período siguiente' : 'Período anterior' } : undefined, index)) };
    if (/Button/.test(name) && ['Day', 'Week', 'Month'].includes(text)) return { onClick: () => setView(text === 'Day' ? 'day' : text === 'Week' ? 'week' : 'month'), props: { 'aria-pressed': view === (text === 'Day' ? 'day' : text === 'Week' ? 'week' : 'month') }, label: text === 'Day' ? 'Vista del día' : text === 'Week' ? 'Vista semanal' : 'Vista mensual' };
    if (name === 'Category' && node.tag !== 'p' && ['Meal Planning', 'Physical Activities', 'Appointments/Events'].includes(text)) {
      if(descendants(node).slice(1).some(child=>nodeName(child)==='Category'&&sourceText(child)===text))return undefined;
      const kind = text === 'Meal Planning' ? 'plan' : text === 'Physical Activities' ? 'activity' : 'consult'; return { onClick: () => toggle(kind), props: { 'aria-pressed': !hidden.has(kind),style:{opacity:hidden.has(kind)?.5:1} }, label: `Mostrar ${kindLabel[kind].toLocaleLowerCase('es')}` };
    }
    if (/Button/.test(name) && text === 'New Schedule') return { onClick: () => onNavigate('mensajes'), label: 'Consultar un turno' };
    return undefined;
  };
  return <FramePair nodes={['84:1666', '433:17250']} resolve={resolver} patientName={patient.name} onNavigate={onNavigate} onSignOut={onSignOut}>{(!plan.data || plan.error) && <Stateful loading={!plan.data && !plan.error} error={plan.error || undefined} onRetry={plan.reload} />}{error && <Stateful error={error} />}{status && <p role="status" className="p-[16px] text-[#272932]">{status}</p>}<p className="mx-[24px] text-[12px] text-[#8a8c90]">Las comidas corresponden a las fechas del plan publicado. Fechas y horas de Argentina. Para acordar otro turno, escribile a tu nutricionista.</p>{patient.appointment && <button type="button" onClick={() => { setError(''); setChanging(true); }} className="mx-[24px] mb-[16px] rounded-[8px] border border-[#e1e1e2] px-[16px] py-[8px]">Cambiar horario de mi consulta</button>}{changing && <RecordDialog title="Cambiar horario de mi consulta" onClose={closeReschedule} busy={busy} dirty={rescheduleDirty}><form onSubmit={event => void reschedule(event)} className="flex w-full max-w-[420px] flex-col gap-[16px] rounded-[16px] bg-white p-[24px]"><h2 className="text-[22px] font-medium">Cambiar horario</h2><label>Día<select value={proposedDay} onChange={event => setProposedDay(event.target.value)} className="mt-[4px] w-full rounded-[8px] border border-[#e1e1e2] p-[10px]">{weekdays.map(day => <option key={day}>{day}</option>)}</select></label><label>Hora<input required type="time" value={proposedTime} onChange={event => setProposedTime(event.target.value)} className="mt-[4px] w-full rounded-[8px] border border-[#e1e1e2] p-[10px]" /></label>{error && <Stateful error={error} />}<div className="flex gap-[8px]"><button type="submit" disabled={busy} className="rounded-[8px] bg-[#c2e66e] px-[16px] py-[10px] text-[#272932]">{busy ? 'Guardando…' : 'Guardar horario'}</button><button type="button" disabled={busy} onClick={closeReschedule} className="rounded-[8px] border border-[#e1e1e2] px-[16px] py-[10px]">Cancelar</button></div></form></RecordDialog>}</FramePair>;
}
