import { NUTRIENTS } from '../../types/foods';
import { PlanRecipeProposalEditor } from './PlanRecipeProposalEditor';
import { componentGrams, componentNutrients, componentTitle, type PlanComponentView } from '../../types/plan-components';
import { NvButton } from './primitives';
import { PlanRecipePreview } from './PlanRecipePicker';

export function PlanComponentRows({ components, onChange }: { components: PlanComponentView[]; onChange: (components: PlanComponentView[]) => void }) {
  function update(index: number, patch: Partial<PlanComponentView>) { onChange(components.map((component, position) => position === index ? { ...component, ...patch } as PlanComponentView : component)); }
  return <div className="plan-component-rows">{components.map((component, index) => {
    const nutrients = componentNutrients(component);
    return <article key={component.id} className="plan-component-row"><div className="plan-component-main"><div><strong>{componentTitle(component)}</strong><small>{component.kind === 'food' ? `${component.food_snapshot?.source ?? 'Sin fuente'} · r${component.food_revision}` : component.kind === 'recipe' ? `Receta publicada · v${component.recipe_version}` : component.recipe_proposal ? 'Propuesta IA · borrador' : 'Indicación libre'}</small></div>
      {component.kind === 'food' ? <><label>Cantidad<input aria-label={`Cantidad del componente ${index + 1}`} type="number" min="0.0001" max="100000" step="0.0001" value={Number.isFinite(component.quantity) ? component.quantity : ''} onChange={event => update(index, { quantity: event.target.value === '' ? NaN : Number(event.target.value) })} /></label><label>Medida<select aria-label={`Medida del componente ${index + 1}`} value={component.measure ?? ''} onChange={event => update(index, { measure: event.target.value || null })}><option value="">Gramos</option>{component.food_snapshot?.portions.map(portion => <option key={portion.name} value={portion.name}>{portion.name}</option>)}</select></label></> : component.kind === 'recipe' ? <label>Porciones<input aria-label={`Porciones del componente ${index + 1}`} type="number" min="0.0001" max="50" step="0.0001" value={Number.isFinite(component.portions) ? component.portions : ''} onChange={event => update(index, { portions: event.target.value === '' ? NaN : Number(event.target.value) })} /></label> : <label>Indicación<input value={component.free_text} maxLength={150} onChange={event => update(index, { free_text: event.target.value, ...(component.recipe_proposal ? { recipe_proposal: { ...component.recipe_proposal, title: event.target.value } } : {}) })} /></label>}
      <span>{nutrients?.kcal == null ? 'Sin dato' : `${nutrients.kcal.toLocaleString('es-AR', { maximumFractionDigits: 2 })} kcal`}</span><button type="button" aria-label={`Quitar ${componentTitle(component)}`} onClick={() => onChange(components.filter((_, position) => position !== index))}>×</button></div>
      <details><summary>Detalle y nota de {componentTitle(component)}</summary>
        {component.kind === 'recipe' && component.recipe_snapshot && <PlanRecipePreview recipe={component.recipe_snapshot} portions={component.portions} />}
        {component.kind === 'food' && <><p>{componentGrams(component)?.toLocaleString('es-AR') ?? 'Cantidad inválida'} g · Revisión {component.food_revision}. La composición guardada se conserva.</p><dl className="plan-recipe-nutrients">{NUTRIENTS.map(([key, label, unit]) => <div key={key}><dt>{label}</dt><dd>{nutrients?.[key] == null ? 'Sin dato' : `${nutrients[key]!.toLocaleString('es-AR', { maximumFractionDigits: 2 })} ${unit}`}</dd></div>)}</dl></>}
        {component.kind === 'text' && component.recipe_proposal && <><p>Propuesta de IA. Revisá ingredientes y preparación antes de publicar.</p><label>Porciones<input type="number" min="0.0001" max="50" step="0.0001" value={Number.isFinite(component.portions) ? component.portions : ''} onChange={event => update(index, { portions: event.target.value === '' ? NaN : Number(event.target.value) })} /></label><PlanRecipeProposalEditor proposal={component.recipe_proposal} index={index} onChange={recipe_proposal => update(index, { recipe_proposal })} /></>}
        <label>Nota para la paciente<input maxLength={200} value={component.public_note} onChange={event => update(index, { public_note: event.target.value })} /></label>
      </details>
    </article>;
  })}<NvButton type="button" className="nv-ghost" disabled={components.length >= 12} onClick={() => onChange([...components, { kind: 'text', id: crypto.randomUUID(), free_text: '', public_note: '' }])}>Agregar indicación libre a la comida</NvButton></div>;
}
