import {useEffect,useRef,useState,type FormEvent} from 'react';
import {resourcesApi} from '../../api/resources';
import {careErrorMessage} from '../../api/care';
import type {EditorialResource} from '../../types/resources';
import {NvButton,NvState} from './primitives';
import {canLeaveWorkspace,useUnsavedChanges} from './unsaved-changes';

type Draft=Pick<EditorialResource,'slug'|'title'|'summary'|'category'|'sections'>;
const newDraft=():Draft=>({slug:`recurso-${crypto.randomUUID()}`,title:'',summary:'',category:'',sections:[{title:'',body:''}]});
export function ProfessionalResourceEditor({onCatalog}:{onCatalog:(resources:EditorialResource[])=>void}) {
  const [catalog,setCatalog]=useState<EditorialResource[]|null>(null),[draft,setDraft]=useState<Draft|null>(null),[baseline,setBaseline]=useState('');
  const [error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
  const lock=useRef(false);const callback=useRef(onCatalog);callback.current=onCatalog;
  useUnsavedChanges(Boolean(draft&&JSON.stringify(draft)!==baseline),busy);
  useEffect(()=>{const controller=new AbortController();setError('');resourcesApi.catalog(controller.signal).then(result=>{if(!controller.signal.aborted){setCatalog(result.resources);callback.current(result.resources);}}).catch(e=>{if(!controller.signal.aborted)setError(careErrorMessage(e));});return()=>controller.abort();},[revision]);
  const open=(source?:EditorialResource)=>{if(!canLeaveWorkspace())return;const next=source?{...newDraft(),title:source.title,summary:source.summary,category:source.category,sections:source.sections.map(s=>({...s}))}:newDraft();setDraft(next);setBaseline(JSON.stringify(next));setStatus('');};
  async function save(event:FormEvent){event.preventDefault();if(!draft||lock.current)return;lock.current=true;setBusy(true);setError('');setStatus('');try{const written=await resourcesApi.save(draft);const read=await resourcesApi.catalog();if(!read.resources.some(r=>r.id===written.resource.id&&r.title===written.resource.title&&JSON.stringify(r.sections)===JSON.stringify(written.resource.sections)))throw Error('El recurso se guardó, pero falta confirmar su lectura. Recargá el catálogo antes de repetir.');setCatalog(read.resources);callback.current(read.resources);setDraft(null);setStatus('Borrador guardado. Revisá su contenido antes de publicarlo.');}catch(e){setError(careErrorMessage(e));}finally{lock.current=false;setBusy(false);}}
  async function publish(resource:EditorialResource){if(lock.current||!canLeaveWorkspace())return;lock.current=true;setBusy(true);setError('');setStatus('');try{await resourcesApi.publish(resource.id);const read=await resourcesApi.catalog();if(!read.resources.some(r=>r.id===resource.id&&r.published))throw Error('Falta confirmar la publicación. Recargá el catálogo.');setCatalog(read.resources);callback.current(read.resources);setStatus('Recurso publicado. Ya se puede asignar a los pacientes.');}catch(e){setError(careErrorMessage(e));}finally{lock.current=false;setBusy(false);}}
  return <section className="pw-safety" aria-label="Edición de recursos"><header className="pw-work-head"><div><h3>Recursos del consultorio</h3><p>Creá materiales y revisá su contenido. Cada nueva versión conserva el recurso anterior y sus asignaciones.</p></div><NvButton disabled={busy} onClick={()=>open()}>Nuevo recurso</NvButton></header>
    {error&&<p role="alert">{error} <button type="button" disabled={busy} onClick={()=>setRevision(r=>r+1)}>Recargar recursos</button></p>}{status&&<p role="status">{status}</p>}
    {draft&&<form className="cbz-form" aria-label="Editar recurso" onSubmit={save}><fieldset disabled={busy}><label>Título<input required minLength={2} maxLength={150} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Resumen<textarea required minLength={2} maxLength={400} value={draft.summary} onChange={e=>setDraft({...draft,summary:e.target.value})}/></label><label>Categoría<input required minLength={2} maxLength={40} value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/></label>{draft.sections.map((section,index)=><div key={index}><label>Título de sección {index+1}<input required maxLength={80} value={section.title} onChange={e=>setDraft({...draft,sections:draft.sections.map((s,i)=>i===index?{...s,title:e.target.value}:s)})}/></label><label>Contenido {index+1}<textarea required maxLength={800} value={section.body} onChange={e=>setDraft({...draft,sections:draft.sections.map((s,i)=>i===index?{...s,body:e.target.value}:s)})}/></label><button type="button" disabled={draft.sections.length===1} onClick={()=>setDraft({...draft,sections:draft.sections.filter((_,i)=>i!==index)})}>Quitar sección</button></div>)}<button type="button" disabled={draft.sections.length===8} onClick={()=>setDraft({...draft,sections:[...draft.sections,{title:'',body:''}]})}>Agregar sección</button></fieldset><div className="cbz-actions"><NvButton type="submit" disabled={busy}>Guardar recurso</NvButton><NvButton className="nv-soft" disabled={busy} onClick={()=>{if(canLeaveWorkspace())setDraft(null);}}>Cerrar editor</NvButton></div></form>}
    {!catalog&&!error?<NvState kind="loading" title="Consultando recursos…" description="Estamos buscando el material del consultorio."/>:<div className="pw-resource-catalog">{catalog?.map(resource=><article key={resource.id}><h4>{resource.title}</h4><p>{resource.published?'Publicado':'Borrador privado'} · {resource.category}</p><details><summary>Revisar contenido</summary><p>{resource.summary}</p>{resource.sections.map((s,i)=><section key={i}><h5>{s.title}</h5><p>{s.body}</p></section>)}<p>Autoría: {resource.author_name}</p></details><div className="cbz-actions"><NvButton className="nv-soft" disabled={busy} onClick={()=>open(resource)}>Crear nueva versión</NvButton>{resource.nutritionist_id&&!resource.published&&<NvButton disabled={busy} onClick={()=>void publish(resource)}>Publicar recurso</NvButton>}</div></article>)}</div>}
  </section>;
}
