import type {IconName} from '../shared/Icon';

export type ProfessionalModule = {id:string;title:string;group:string;icon:IconName;href?:string;current:string[];next:string[]};
/** Product scope, not a release claim: availability refers to this development branch. */
export const PROFESSIONAL_MODULES:ProfessionalModule[] = [
  {id:'inicio',title:'Inicio',group:'Consultorio',icon:'home',href:'/crm/inicio',current:['Bandeja de ingresos, comidas, registros, propuestas IA, mensajes, pagos y consultas.','Filtros y acceso a la ficha correspondiente.'],next:['Indicadores y comparación por período.','Tendencias de consultas e ingresos y próximas acciones.']},
  {id:'pacientes',title:'Pacientes y ficha',group:'Consultorio',icon:'users',href:'/crm/pacientes',current:['Alta, invitación, vinculación, búsqueda, etapas y archivo.','Ficha, ingreso y antecedentes, objetivos e historial.','Accesos al plan, consultas, mensajes y cobranzas.'],next:['Última consulta, conexión y columnas configurables.','Completar anamnesis y solicitud de reapertura profesional.']},
  {id:'agenda',title:'Agenda y consultas',group:'Consultorio',icon:'calendar',href:'/crm/agenda',current:['Turnos, duración, videollamada, confirmación y reprogramación.','Consulta en curso visible hasta su finalización.'],next:['Disponibilidad, tipos de consulta, solicitudes y reservas.','Recordatorios y conexión con página pública.']},
  {id:'cobranzas',title:'Cobranzas',group:'Consultorio',icon:'wallet',href:'/crm/cobranzas',current:['Cuotas, vencimientos, avisos y confirmación manual de pagos.','Historial y estado de acceso de cada paciente.'],next:['Evitar duplicados al modificar vencimientos.','Mercado Pago, enlaces, conciliación y programas recurrentes.','Paquetes de sesiones.']},
  {id:'seguimiento',title:'Seguimiento',group:'Acompañamiento',icon:'sparkle',href:'/crm/seguimiento',current:['Bandeja de comidas y registros pendientes de revisión.','Registro semanal: días, comidas y agua separados en directorio y ficha.','Novedades de la cartera con filtros de período, revisión y paciente, y detalle por día.','Escribirle a cada paciente desde las novedades.'],next:['Ánimo y síntomas (la app de la paciente todavía no los registra).']},
  {id:'mensajes',title:'Mensajes y avisos',group:'Acompañamiento',icon:'message',href:'/crm/mensajes',current:['Conversaciones y adjuntos privados.','Avisos del consultorio y acceso a pendientes.'],next:['No leídos y actualización de toda la cartera sin recargar.','Historial paginado y estados de entrega coherentes.','Preferencias y canales de avisos; especificar bloqueo y denuncia.']},
  {id:'mediciones',title:'Mediciones y evolución',group:'Acompañamiento',icon:'trend',href:'/crm/pacientes',current:['Peso y medidas opcionales con consentimiento.','Historial, origen y evolución por períodos desde la ficha.'],next:['Composición corporal, perímetros y carga agrupada.','Detalle mínimo, promedio y máximo.','Importar informes de balanza con revisión de unidades, fechas y duplicados; IA/OCR cuando corresponda.']},
  {id:'progreso-global',title:'Progreso global',group:'Acompañamiento',icon:'trend',current:[],next:['Vista longitudinal de la cartera.','Indicadores separados por período, sin interpretar falta de registros como incumplimiento.']},
  {id:'asistente-ia',title:'Asistente IA',group:'Acompañamiento',icon:'sparkle',current:[],next:['Chat y preguntas sugeridas sobre la cartera.','Resúmenes y propuestas contextualizadas.','Fuentes y motivos visibles; revisión profesional antes de ejecutar acciones.','Usar la API de IA existente.']},
  {id:'planificacion',title:'Planificación nutricional',group:'Planes y alimentos',icon:'target',href:'/crm/pacientes',current:['Meta, IMC y referencias generales; comparación con la confirmada.','Actualizar objetivo del borrador al confirmar la meta, conservando el publicado.','Comparar Mifflin-St Jeor con Harris-Benedict, FAO/OMS/ONU, Katch-McArdle y el basal de la balanza.'],next:['Elegir otra fórmula como base de la meta y referencias de composición corporal.','Revalidar propuestas IA cuando cambia la meta.','Objetivos sin peso numérico obligatorio.']},
  {id:'planes',title:'Planes y análisis',group:'Planes y alimentos',icon:'list',href:'/crm/plan',current:['Editor semanal, componentes, copia de días y versiones.','Promedio nutricional, recomendaciones y alimentos a evitar.','Revisión de propuestas IA, publicación e impresión.'],next:['Momentos personalizados y horarios.','Distribución y micronutrientes con referencias.','Aviso al publicar y transición entre versiones/fechas.','Impresión con logo, tablas y descarga directa.']},
  {id:'alimentos',title:'Alimentos',group:'Planes y alimentos',icon:'leaf',href:'/crm/alimentos',current:['Catálogo, búsqueda, creación, edición y detalle nutricional.'],next:['Fuentes externas autorizadas y más nutrientes/referencias.']},
  {id:'recetas',title:'Recetas',group:'Planes y alimentos',icon:'leaf',href:'/crm/biblioteca?biblioteca=recetas',current:['Catálogo, editor en ventana, ingredientes y porciones.','Propuestas IA personalizadas y versiones publicadas.','Asignación al plan y control de alergias/restricciones.'],next:['Propuestas IA generales sin elegir paciente.','Recuperar propuestas IA después de recargar.','Ampliación de nutrientes y fuentes.']},
  {id:'equivalencias',title:'Equivalencias',group:'Planes y alimentos',icon:'list',current:[],next:['Catálogo y selector de alternativas aprobadas.','Cantidades equivalentes y justificación visibles.','Uso en alimentos, recetas y planes.']},
  {id:'modelos',title:'Modelos',group:'Planes y alimentos',icon:'list',href:'/crm/modelos',current:['Modelos de planes, recomendaciones y alimentos a evitar.','Aplicar al nuevo borrador conservando la versión anterior.','Agregar indicaciones sin duplicados.'],next:['Ampliar alternativas reutilizables según evolución del editor.']},
  {id:'recursos',title:'Biblioteca y recursos',group:'Herramientas',icon:'pin',href:'/crm/biblioteca?biblioteca=recursos',current:['Recursos, asignación, lectura y favoritos.','Adjuntos privados, fotos y estudios con permisos.'],next:['Autor real y despublicación de artículos.','Pedido de estudios enviable/imprimible y adjuntos a notas.','Meta individual de agua y actividad recomendada visibles para paciente.']},
  {id:'pagina-publica',title:'Página pública',group:'Herramientas',icon:'contact',current:[],next:['Perfil del consultorio, servicios y programas.','Solicitud, reserva y pago conectados a agenda.','Vista previa y publicación profesional.']},
  {id:'ayuda',title:'Centro de ayuda',group:'Herramientas',icon:'message',current:[],next:['Guías por función y ayuda contextual.','Recuperación de errores y soporte del consultorio.']},
  {id:'configuracion',title:'Configuración y reportes',group:'Herramientas',icon:'grid',current:[],next:['Perfil, logo y preferencias del consultorio.','Reportes y exportaciones.','Equipos, suscripciones y Meta Pixel/Ads requieren alcance propio.']},
];

export const plannedModuleHref=(id:string)=>`/crm/desarrollo?modulo=${encodeURIComponent(id)}`;
