import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {writeFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
const run=promisify(execFile), browse=process.env.PLANV_GSTACK_CLI;
if(!browse)throw Error('Falta gstack');
const origin='http://127.0.0.1:5606', api='http://127.0.0.1:5607';
const env={...process.env,BROWSE_PARENT_PID:'0',BROWSE_STATE_FILE:resolve('.gstack/crm-verified-state.json')};
let phase='inicio';const evidence=[],metrics=[];
async function B(...args){return(await run(browse,args,{env,timeout:25000,maxBuffer:2e6})).stdout.trim();}
async function until(expression){const end=Date.now()+15000;while(Date.now()<end){if((await B('js',expression)).includes('true'))return;await new Promise(r=>setTimeout(r,150));}throw Error('No se confirmó '+phase+': '+expression);}
async function button(label){await until(`(()=>{const e=Array.from(document.querySelectorAll('button')).find(e=>e.textContent.trim()===${JSON.stringify(label)}&&!e.disabled&&e.getClientRects().length);if(!e)return false;e.click();return true})()`);}
async function goto(path){await B('goto',origin+path);await until("document.querySelector('input[placeholder=Email],.nv-app,[data-figma-frame]')!==null");if((await B('js',"document.body.innerText.includes('Continuar en modo demo')")).includes('true'))await button('Continuar en modo demo');await until("!document.body.innerText.includes('Cargando pantalla…')");}
function check(condition,label){if(!condition)throw Error(label);evidence.push(label);console.log('Verificado: '+label);}
async function write(path,method,data){const r=await fetch(api+path,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw Error('Escritura falló '+r.status);return r.json();}
async function read(path){const r=await fetch(api+path);if(!r.ok)throw Error('Lectura falló '+r.status);return r.json();}
try{
await mkdir('.gstack',{recursive:true});await goto('/crm/inicio');
if((await B('js',"document.body.innerText.includes('Continuar en modo demo')")).includes('true'))await button('Continuar en modo demo');
await until("document.querySelector('.pw-work')!==null");check((await read('/api/crm/work-queue')).items.length>0,'bandeja real devuelve tareas');
phase='ficha';await goto('/crm/ficha?paciente=pat-sofia');await button('Ingreso y antecedentes');await B('fill','textarea','Nota privada sin guardar');
await B('js','window.confirm=()=>false;history.back()');await until("document.querySelector('textarea')?.value==='Nota privada sin guardar'&&location.search.includes('seccion=ingreso')");check(true,'cancelar Atrás conserva pestaña y nota');
await B('select','[aria-label="Paciente del consultorio"]','pat-marina');check((await B('js',"document.querySelector('textarea')?.value==='Nota privada sin guardar'&&location.search.includes('pat-sofia')")).includes('true'),'cancelar cambio de paciente conserva formulario');
await button('Guardar observación profesional');await until("document.querySelector('textarea')?.value===''");await B('js','window.confirm=()=>true');
phase='preparar ingreso ficticio';const intake=(await read('/api/patients/pat-sofia/intake')).intake;if(intake.status==='draft')await write('/api/patients/pat-sofia/intake','PATCH',{expected_revision:intake.revision,payload:{preferred_name:'Sofía',allergies:{state:'none',items:[]},restrictions:{state:'none',items:[]}}});for(const c of (await read('/api/consents/catalog')).consents.filter(c=>['care_relationship','ai_menu_draft'].includes(c.purpose)))await write('/api/patients/pat-sofia/consents','POST',{purpose:c.purpose,text_version:c.text_version,text_hash:c.text_hash,decision:'granted'});
phase='plan';await goto('/crm/plan?paciente=pat-sofia');await until("document.querySelector('.meal-plan-form')!==null");
const date=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Argentina/Buenos_Aires',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
await B('fill','.meal-plan-form input[type="date"]',date).catch(async()=>{await B('js',`(()=>{const e=document.querySelector('.meal-plan-form input[type=date]');const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;set.call(e,${JSON.stringify(date)});e.dispatchEvent(new Event('input',{bubbles:true}));return true})()`)});
await B('js',`(()=>{const list=document.querySelectorAll('.meal-plan-form input[type=date]');const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;for(const e of list){set.call(e,${JSON.stringify(date)});e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));}return true})()`);
await B('fill','[aria-label="Texto 1"]','Plato revisado del recorrido');await B('fill','[aria-label="Nota 1"]','Indicación pública verificada');await button('Guardar borrador');await until("document.body.innerText.includes('Borrador guardado')");
const stored=(await read('/api/patients/pat-sofia/plans?audience=pro')).plan;check(Boolean(stored),'borrador leído después de guardar');await button('Publicar v'+stored.current.version);await until("document.body.innerText.includes('Plan publicado')");
const published=(await read('/api/patients/pat-sofia/plans')).plan;check(published.items[0].public_note==='Indicación pública verificada','publicación confirma mismo contenido para paciente');
await B('js','window.confirm=()=>false');
phase='IA revisada';await button('Generar propuesta de menú');await until("document.querySelector('.meal-plan-proposal')!==null");await button('Editar propuesta');await until("document.body.innerText.includes('Propuesta guardada como borrador privado')");const aiDraft=(await read('/api/patients/pat-sofia/plans?audience=pro')).plan;for(let i=0;i<aiDraft.current.items.length;i++)await B('fill','[aria-label="Texto '+(i+1)+'"]','Preparación revisada '+(i+1));await B('fill','[aria-label="Nota 1"]','Menú IA corregido por profesional');await button('Guardar borrador');await until("document.body.innerText.includes('Borrador guardado')");const reviewedAI=(await read('/api/patients/pat-sofia/plans?audience=pro')).plan;await button('Publicar v'+reviewedAI.current.version);await until("document.body.innerText.includes('Plan publicado')");check((await read('/api/patients/pat-sofia/plans')).plan.items[0].public_note==='Menú IA corregido por profesional','IA editada y publicada conserva corrección visible para paciente');
phase='biblioteca';await goto('/crm/biblioteca?paciente=pat-sofia&biblioteca=recursos');await until("document.querySelector('.nvw-resource-picker')!==null");check(true,'biblioteca permite asignar recursos');await button('Nuevo recurso');await B('fill','form[aria-label="Editar recurso"] input[maxlength="150"]','Guía ficticia QA');await B('fill','form[aria-label="Editar recurso"] textarea[maxlength="400"]','Resumen ficticio revisado');await B('fill','form[aria-label="Editar recurso"] input[maxlength="40"]','Hábitos');await B('fill','form[aria-label="Editar recurso"] label input[maxlength="80"]','Sección ficticia');await B('fill','form[aria-label="Editar recurso"] label textarea[maxlength="800"]','Contenido ficticio publicado');await button('Guardar recurso');await until("document.body.innerText.includes('Borrador guardado. Revisá su contenido')");await B('click','.pw-resource-catalog article:has-text("Guía ficticia QA") button:has-text("Publicar recurso")');await until("document.body.innerText.includes('Recurso publicado')");await B('click','.nvw-resource-picker button:has-text("Guía ficticia QA")');await B('click','[aria-label="Seleccionar Sofía R."]');await button('Asignar a 1');await until("document.body.innerText.includes('1 asignación creada.')");const library=(await read('/api/patients/pat-sofia/library')).library;const custom=library.articles.find(r=>r.title==='Guía ficticia QA');check(Boolean(custom),'recurso creado, publicado y asignado se relee desde paciente');
phase='cobros';await goto('/crm/cobranzas?paciente=pat-sofia');await until("document.querySelector('#cbz-fee-amount')!==null");await B('fill','#cbz-fee-amount','1200');await B('fill','#cbz-fee-due',date);await button((await read('/api/patients/pat-sofia/ledger?audience=patient')).ledger.fee?'Cambiar cuota':'Guardar cuota');await until("document.querySelector('.cbz-panel-head')?.textContent.includes('1.200')");check((await read('/api/patients/pat-sofia/ledger?audience=patient')).ledger.fee.amount===1200,'cuota actualizada coincide desde paciente');
phase='receta para detalle';const recipeDraft=await write('/api/recipes','POST',{id:crypto.randomUUID(),expected_revision:null,title:'Receta ficticia QA',yield_portions:2,steps:['Preparar y servir.'],nutrient_source:'Tabla declarada ficticia',category:'Almuerzo',prep_minutes:null,kcal:200,protein_g:10,carbs_g:30,fat_g:5,items:[{name:'Arroz',quantity:100,unit:'g'}]});await write('/api/recipes/'+recipeDraft.recipe.id+'/publish','POST',{expected_version:recipeDraft.recipe.current.version,expected_revision:recipeDraft.recipe.current.revision});await write('/api/recipes/'+recipeDraft.recipe.id+'/assign','POST',{patient_id:'pat-sofia',expected_version:recipeDraft.recipe.current.version});
phase='paciente';await goto('/app/inicio');await until("document.querySelector('[data-figma-frame]')!==null");
for(const size of ['1440x1000','390x844','1024x900','1280x900','360x800']){
 await B('viewport',size);for(const page of ['inicio','agenda','mensajes','recetas','plan','compras','diario','progreso','ejercicio','recursos']){
  phase=page+' '+size;await goto('/app/'+page);await until("document.querySelector('[data-figma-frame]')!==null&&!document.querySelector('[data-figma-frame]').textContent.includes('Cargando pantalla…')");
  const raw=await B('js',`JSON.stringify({page:${JSON.stringify(page)},size:${JSON.stringify(size)},frame:document.querySelector('[data-figma-frame]').dataset.figmaFrame,viewport:innerWidth,document:document.documentElement.scrollWidth,sourceWidth:document.querySelector('[data-figma-frame]')?.firstElementChild?.getBoundingClientRect().width,body:document.body.innerText.includes('No se pudo cargar esta pantalla')})`);metrics.push(JSON.parse(raw));if(page==='recursos'){await until("document.querySelector('[aria-label=\"Leer Guía ficticia QA\"]')!==null");await B('click','[aria-label="Leer Guía ficticia QA"]');await until("['279:9301','507:17412'].includes(document.querySelector('[data-figma-frame]')?.dataset.figmaFrame)&&document.body.innerText.includes('Contenido ficticio publicado')");check(true,'detalle de recurso muestra el contenido real '+size);metrics.push(JSON.parse(await B('js',`JSON.stringify({page:'recurso',size:${JSON.stringify(size)},frame:document.querySelector('[data-figma-frame]').dataset.figmaFrame,viewport:innerWidth,document:document.documentElement.scrollWidth})`)));}
 }
 await goto('/app/recetas');await until("document.querySelector('[data-figma-frame]')!==null");await until("(()=>{const b=Array.from(document.querySelectorAll('button')).find(e=>e.getClientRects().length&&e.getAttribute('aria-label')?.startsWith('Ver ')&&e.textContent.includes('Ver receta'));if(!b)return false;b.click();return true})()");await until("['84:3145','457:13264'].includes(document.querySelector('[data-figma-frame]')?.dataset.figmaFrame)");metrics.push(JSON.parse(await B('js',`JSON.stringify({page:'receta',size:${JSON.stringify(size)},frame:document.querySelector('[data-figma-frame]').dataset.figmaFrame,viewport:innerWidth,document:document.documentElement.scrollWidth})`)));console.log('Medidas comprobadas: '+size);
}
await writeFile('.gstack/crm-demo-evidence.json',JSON.stringify({evidence,metrics},null,2));console.log('Recorrido finalizado');
}catch(e){await writeFile('.gstack/crm-demo-evidence.json',JSON.stringify({phase,error:e.message,diagnostic:await B('js',"JSON.stringify({href:location.href,textarea:document.querySelector('textarea')?.value,active:document.querySelector('[aria-current=page]')?.textContent,alerts:Array.from(document.querySelectorAll('[role=alert]')).map(e=>e.textContent)})").catch(()=>''),evidence,metrics},null,2));console.error('Fallo en '+phase+': '+e.message);process.exitCode=1;}
